input:
  dir_path: output/test_vinai_overfit_fov180/point_clouds
  pattern: 'pcd_val*.ply'
output:
  out_dir: output/test_vinai_overfit_fov180
  out_name: pcd_vis_topview_crop
  fps: 2
  width: 800
  height: 800
visualization:
  point_size: 2.0
  min_bound: [-40, -10, -0.5]
  max_bound: [40, 10, 8]
camera_param_file: scripts/pcd_visualization/configs/camera_params_topview_vinai.json
